<div class="textile">
	<p>Quick block modifiers:<br />

Header: <strong>h<em>n</em>.</strong> <a target="_blank" href="http://www.textpattern.com/help/?item=header" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

Blockquote: <strong>bq.</strong> <a target="_blank" href="http://www.textpattern.com/help/?item=blockquote" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

Numeric list: <strong>#</strong> <a target="_blank" href="http://www.textpattern.com/help/?item=numeric" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

Bulleted list: <strong>*</strong> <a target="_blank" href="http://www.textpattern.com/help/?item=bulleted" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />		</p>

		<p>Quick phrase modifiers:<br />
_<em>emphasis</em>_ <a target="_blank" href="http://www.textpattern.com/help/?item=italic" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

*<strong>strong</strong>* <a target="_blank" href="http://www.textpattern.com/help/?item=bold" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

??<cite>citation</cite>?? <a target="_blank" href="http://www.textpattern.com/help/?item=cite" onclick="window.open(this.href, 'popupwindow', 'width=500,height=300,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

^superscript^ <a target="_blank" href="http://www.textpattern.com/help/?item=super" onclick="window.open(this.href, 'popupwindow', 'width=400,height=300,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

~subscript~ <a target="_blank" href="http://www.textpattern.com/help/?item=sub" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />

@code@ <a target="_blank" href="http://www.textpattern.com/help/?item=code" onclick="window.open(this.href, 'popupwindow', 'width=400,height=400,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />	
		</p>

		<p>To insert a link:<br />
	"linktext":url <a target="_blank" href="http://www.textpattern.com/help/?item=link" onclick="window.open(this.href, 'popupwindow', 'width=400,height=500,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />		</p>
		<p>To insert an image:<br />
	!imageurl! <a target="_blank" href="http://www.textpattern.com/help/?item=image" onclick="window.open(this.href, 'popupwindow', 'width=500,height=500,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />		</p>
		<p>To define an acronym:<br />

	ABC(Always Be Closing) <a target="_blank" href="http://www.textpattern.com/help/?item=acronym" onclick="window.open(this.href, 'popupwindow', 'width=500,height=500,scrollbars,resizable'); return false;" style="color:blue;background-color:#ddd">?</a><br />		</p>	

		<p>To make a new section:<br />
	---<br />		</p>	
	
		<p>No Textilisation:<br />
	==notextile==</p>	

</div>